<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9</LangVersion>
    <RootNamespace>DocSets.Import</RootNamespace>
    <AssemblyName>DocSets.Import</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocSets.Model\DocSets.Model.csproj" />
    <ProjectReference Include="..\DocSets.Serialization\DocSets.Serialization.csproj" />
    <ProjectReference Include="..\DocSets.Core\DocSets.Core.csproj" />
  </ItemGroup>
</Project>
