<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>DocSets.IntegrationTests</RootNamespace>
    <AssemblyName>DocSets.IntegrationTests</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <VsIdeDir Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)</VsIdeDir>
    <VsIdeDir Condition="'$(VsIdeDir)' == ''">$(MSBuildToolsPath)\..\..\..\Common7\IDE\</VsIdeDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework">
      <HintPath>..\DocSets.Tests\lib\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.Office.Interop.OneNote, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c, processorArchitecture=MSIL">
      <HintPath>$(WINDIR)\assembly\GAC_MSIL\Microsoft.Office.Interop.OneNote\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.OneNote.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocSets.Model\DocSets.Model.csproj" />
    <ProjectReference Include="..\DocSets.Serialization\DocSets.Serialization.csproj" />
    <ProjectReference Include="..\DocSets.Core\DocSets.Core.csproj" />
    <ProjectReference Include="..\DocSets.Editor.Jodit\DocSets.Editor.Jodit.csproj" />
    <ProjectReference Include="..\DocSets.UI.WinForms\DocSets.UI.WinForms.csproj" />
    <Compile Include="..\DocSets.Tests\TestFramework.cs" Link="TestFramework.cs" />
    <Compile Include="..\DocSets.Desktop\OneNote\OneNoteImportModels.cs" Link="OneNote\OneNoteImportModels.cs" />
    <Compile Include="..\DocSets.Desktop\OneNote\OneNoteImportService.cs" Link="OneNote\OneNoteImportService.cs" />
  </ItemGroup>
</Project>
